{% set name = "hvac" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b85e3320e8642dd82f234db63253cda169a817589e823713dc5fca83119b1e2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - requests >=2.27.1,<3.0.0
  run_constrained:
    - pyhcl >=0.4.4,<0.5.0

test:
  imports:
    - hvac
    - hvac.api
    - hvac.api.auth_methods
    - hvac.api.secrets_engines
    - hvac.api.system_backend
    - hvac.constants
    - hvac.v1
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://python-hvac.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: HashiCorp Vault API client
  doc_url: https://hvac.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/hvac/hvac

extra:
  recipe-maintainers:
    - mbiette
    - mariusvniekerk
