{% set name = "hvac" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64f8d108c6fd65383da4f64889f5bd0c684547d753713784fbe0d0fb71842529

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - requests >=2.21.0
  run:
    - python >=3.6
    - requests >=2.21.0

test:
  imports:
    - hvac
    - hvac.api
    - hvac.api.auth_methods
    - hvac.api.secrets_engines
    - hvac.api.system_backend
    - hvac.constants
    - hvac.v1
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://python-hvac.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: HashiCorp Vault API client
  doc_url: https://hvac.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/hvac/hvac

extra:
  recipe-maintainers:
    - mariusvniekerk
